// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGamesFromDrop(arg1) {
  return window['go']['main']['App']['AddGamesFromDrop'](arg1);
}

export function AddSingleGameManual() {
  return window['go']['main']['App']['AddSingleGameManual']();
}

export function CopyCoverToData(arg1, arg2) {
  return window['go']['main']['App']['CopyCoverToData'](arg1, arg2);
}

export function CopyScreenshotToData(arg1, arg2) {
  return window['go']['main']['App']['CopyScreenshotToData'](arg1, arg2);
}

export function FindExecutables(arg1) {
  return window['go']['main']['App']['FindExecutables'](arg1);
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetScanPath() {
  return window['go']['main']['App']['GetScanPath']();
}

export function Launch(arg1, arg2, arg3) {
  return window['go']['main']['App']['Launch'](arg1, arg2, arg3);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function RemoveGame(arg1) {
  return window['go']['main']['App']['RemoveGame'](arg1);
}

export function ScanLocalFolder(arg1) {
  return window['go']['main']['App']['ScanLocalFolder'](arg1);
}

export function SearchGames(arg1) {
  return window['go']['main']['App']['SearchGames'](arg1);
}

export function SelectCoverImage() {
  return window['go']['main']['App']['SelectCoverImage']();
}

export function SelectExecutable(arg1) {
  return window['go']['main']['App']['SelectExecutable'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectScreenshots() {
  return window['go']['main']['App']['SelectScreenshots']();
}

export function SetScanPath(arg1) {
  return window['go']['main']['App']['SetScanPath'](arg1);
}

export function UpdateGame(arg1) {
  return window['go']['main']['App']['UpdateGame'](arg1);
}

export function UpdateGameMetadata(arg1, arg2) {
  return window['go']['main']['App']['UpdateGameMetadata'](arg1, arg2);
}
