// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGamesFromDrop(arg1) {
  return window['go']['main']['App']['AddGamesFromDrop'](arg1);
}

export function AddScanPath(arg1) {
  return window['go']['main']['App']['AddScanPath'](arg1);
}

export function AddSingleGameManual() {
  return window['go']['main']['App']['AddSingleGameManual']();
}

export function ChangeDataDir(arg1) {
  return window['go']['main']['App']['ChangeDataDir'](arg1);
}

export function CheckAllUpdates() {
  return window['go']['main']['App']['CheckAllUpdates']();
}

export function CheckGameUpdates(arg1) {
  return window['go']['main']['App']['CheckGameUpdates'](arg1);
}

export function CheckLauncherUpdate() {
  return window['go']['main']['App']['CheckLauncherUpdate']();
}

export function CheckSourceUpdate(arg1, arg2) {
  return window['go']['main']['App']['CheckSourceUpdate'](arg1, arg2);
}

export function ClearData() {
  return window['go']['main']['App']['ClearData']();
}

export function ConfigureDataDir(arg1) {
  return window['go']['main']['App']['ConfigureDataDir'](arg1);
}

export function CopyCoverToData(arg1, arg2) {
  return window['go']['main']['App']['CopyCoverToData'](arg1, arg2);
}

export function CopyScreenshotToData(arg1, arg2) {
  return window['go']['main']['App']['CopyScreenshotToData'](arg1, arg2);
}

export function ExportLibrary() {
  return window['go']['main']['App']['ExportLibrary']();
}

export function FindExecutables(arg1) {
  return window['go']['main']['App']['FindExecutables'](arg1);
}

export function FindMissingGames() {
  return window['go']['main']['App']['FindMissingGames']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetCustomLocales() {
  return window['go']['main']['App']['GetCustomLocales']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDefaultDataDir() {
  return window['go']['main']['App']['GetDefaultDataDir']();
}

export function GetDocumentsDataDir() {
  return window['go']['main']['App']['GetDocumentsDataDir']();
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetPortableDataDir() {
  return window['go']['main']['App']['GetPortableDataDir']();
}

export function GetScanPaths() {
  return window['go']['main']['App']['GetScanPaths']();
}

export function GetSupportedSources() {
  return window['go']['main']['App']['GetSupportedSources']();
}

export function ImportLibrary(arg1) {
  return window['go']['main']['App']['ImportLibrary'](arg1);
}

export function InstallLauncherUpdate() {
  return window['go']['main']['App']['InstallLauncherUpdate']();
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function Launch(arg1, arg2, arg3) {
  return window['go']['main']['App']['Launch'](arg1, arg2, arg3);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenLanguagesFolder() {
  return window['go']['main']['App']['OpenLanguagesFolder']();
}

export function OpenLauncherReleasePage() {
  return window['go']['main']['App']['OpenLauncherReleasePage']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RelinkAllFound() {
  return window['go']['main']['App']['RelinkAllFound']();
}

export function RelinkGame(arg1, arg2) {
  return window['go']['main']['App']['RelinkGame'](arg1, arg2);
}

export function RemoveGame(arg1) {
  return window['go']['main']['App']['RemoveGame'](arg1);
}

export function RemoveMissingGames() {
  return window['go']['main']['App']['RemoveMissingGames']();
}

export function RemoveScanPath(arg1) {
  return window['go']['main']['App']['RemoveScanPath'](arg1);
}

export function SaveCollections(arg1) {
  return window['go']['main']['App']['SaveCollections'](arg1);
}

export function SaveWindowSize() {
  return window['go']['main']['App']['SaveWindowSize']();
}

export function ScanAllFolders() {
  return window['go']['main']['App']['ScanAllFolders']();
}

export function ScanLocalFolder(arg1) {
  return window['go']['main']['App']['ScanLocalFolder'](arg1);
}

export function SearchGames(arg1) {
  return window['go']['main']['App']['SearchGames'](arg1);
}

export function SelectBackupFile() {
  return window['go']['main']['App']['SelectBackupFile']();
}

export function SelectCoverImage() {
  return window['go']['main']['App']['SelectCoverImage']();
}

export function SelectDataFolder() {
  return window['go']['main']['App']['SelectDataFolder']();
}

export function SelectExecutable(arg1) {
  return window['go']['main']['App']['SelectExecutable'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectRelinkFolder(arg1) {
  return window['go']['main']['App']['SelectRelinkFolder'](arg1);
}

export function SelectScreenshots() {
  return window['go']['main']['App']['SelectScreenshots']();
}

export function UpdateGame(arg1) {
  return window['go']['main']['App']['UpdateGame'](arg1);
}

export function UpdateGameMetadata(arg1, arg2) {
  return window['go']['main']['App']['UpdateGameMetadata'](arg1, arg2);
}
