// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddGamesFromDrop(arg1:Array<string>):Promise<number>;

export function AddSingleGameManual():Promise<void>;

export function CopyCoverToData(arg1:string,arg2:string):Promise<string>;

export function CopyScreenshotToData(arg1:string,arg2:string):Promise<string>;

export function FindExecutables(arg1:string):Promise<Array<string>>;

export function GetGames():Promise<Array<models.Game>>;

export function GetScanPath():Promise<string>;

export function Launch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function RemoveGame(arg1:string):Promise<void>;

export function ScanLocalFolder(arg1:string):Promise<number>;

export function SearchGames(arg1:string):Promise<Array<models.Game>>;

export function SelectCoverImage():Promise<string>;

export function SelectExecutable(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectScreenshots():Promise<Array<string>>;

export function SetScanPath(arg1:string):Promise<void>;

export function UpdateGame(arg1:models.Game):Promise<void>;

export function UpdateGameMetadata(arg1:string,arg2:string):Promise<void>;
