// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {parser} from '../models';

export function AddGamesFromDrop(arg1:Array<string>):Promise<number>;

export function AddScanPath(arg1:string):Promise<void>;

export function AddSingleGameManual():Promise<void>;

export function ChangeDataDir(arg1:string):Promise<void>;

export function ClearData():Promise<void>;

export function ConfigureDataDir(arg1:string):Promise<void>;

export function CopyCoverToData(arg1:string,arg2:string):Promise<string>;

export function CopyScreenshotToData(arg1:string,arg2:string):Promise<string>;

export function FindExecutables(arg1:string):Promise<Array<string>>;

export function GetCollections():Promise<Array<models.Collection>>;

export function GetCustomLocales():Promise<Record<string, Record<string, string>>>;

export function GetDataDir():Promise<string>;

export function GetDefaultDataDir():Promise<string>;

export function GetDocumentsDataDir():Promise<string>;

export function GetGames():Promise<Array<models.Game>>;

export function GetPortableDataDir():Promise<string>;

export function GetScanPaths():Promise<Array<string>>;

export function GetSupportedSources():Promise<Array<parser.Source>>;

export function IsConfigured():Promise<boolean>;

export function Launch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenDataDir():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenLanguagesFolder():Promise<void>;

export function RemoveGame(arg1:string):Promise<void>;

export function RemoveScanPath(arg1:string):Promise<void>;

export function SaveCollections(arg1:Array<models.Collection>):Promise<void>;

export function SaveWindowSize():Promise<void>;

export function ScanAllFolders():Promise<number>;

export function ScanLocalFolder(arg1:string):Promise<number>;

export function SearchGames(arg1:string):Promise<Array<models.Game>>;

export function SelectCoverImage():Promise<string>;

export function SelectDataFolder():Promise<string>;

export function SelectExecutable(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectScreenshots():Promise<Array<string>>;

export function UpdateGame(arg1:models.Game):Promise<void>;

export function UpdateGameMetadata(arg1:string,arg2:string):Promise<void>;
